//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using Cysharp.Threading.Tasks;
using System.Collections.Generic;


namespace cfg
{
   
public sealed class Tables
{
    public Deer.TbSounds_Config TbSounds_Config {get; private set; }
    public Deer.TbLanguage_Config TbLanguage_Config {get; private set; }
    public Deer.TbEntityData TbEntityData {get; private set; }

    public Tables() { }
    
    public async UniTask LoadAsync(System.Func<string, UniTask<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
		List<UniTask> list = new List<UniTask>();
		list.Add(UniTask.Create(async () =>
		{
			TbSounds_Config = new Deer.TbSounds_Config(await loader("deer_tbsounds_config")); 
			tables.Add("Deer.TbSounds_Config", TbSounds_Config);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbLanguage_Config = new Deer.TbLanguage_Config(await loader("deer_tblanguage_config")); 
			tables.Add("Deer.TbLanguage_Config", TbLanguage_Config);
		}));
		list.Add(UniTask.Create(async () =>
		{
			TbEntityData = new Deer.TbEntityData(await loader("deer_tbentitydata")); 
			tables.Add("Deer.TbEntityData", TbEntityData);
		}));

		await UniTask.WhenAll(list);

        TbSounds_Config.Resolve(tables); 
        TbLanguage_Config.Resolve(tables); 
        TbEntityData.Resolve(tables); 
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbSounds_Config.TranslateText(translator); 
        TbLanguage_Config.TranslateText(translator); 
        TbEntityData.TranslateText(translator); 
    }
}

}